/**
 * Fusion / FBX base names per rack slot.
 * S1–S4: long (standard) umbrella. S5–S8: folding umbrella.
 */
export const UMBRELLA_PART_BASE_NAMES_BY_SLOT: Record<number, readonly string[]> = {
  1: [
    'Handle_Crook_Vert_S1',
    'Handle_Crook_Horiz_S1',
    'Handle_Grip_S1',
    'Shaft_S1',
    'Runner_S1',
    'Ferrule_S1',
    'Canopy_S1',
  ],
  2: [
    'Handle_Crook_Vert_S2',
    'Handle_Crook_Horiz_S2',
    'Handle_Grip_S2',
    'Shaft_S2',
    'Runner_S2',
    'Ferrule_S2',
    'Canopy_S2',
  ],
  3: [
    'Handle_Crook_Vert_S3',
    'Handle_Crook_Horiz_S3',
    'Handle_Grip_S3',
    'Shaft_S3',
    'Runner_S3',
    'Ferrule_S3',
    'Canopy_S3',
  ],
  4: [
    'Handle_Crook_Vert_S4',
    'Handle_Crook_Horiz_S4',
    'Handle_Grip_S4',
    'Shaft_S4',
    'Runner_S4',
    'Ferrule_S4',
    'Canopy_S4',
  ],
  5: [
    'Handle_S5',
    'Wrist_Loop_S5',
    'Shaft_Seg1_S5',
    'Joint_S5_0',
    'Shaft_Seg2_S5',
    'Joint_S5_1',
    'Shaft_Seg3_S5',
    'Runner_S5',
    'Ferrule_S5',
    'Canopy_S5',
  ],
  6: [
    'Handle_S6',
    'Wrist_Loop_S6',
    'Shaft_Seg1_S6',
    'Joint_S6_0',
    'Shaft_Seg2_S6',
    'Joint_S6_1',
    'Shaft_Seg3_S6',
    'Runner_S6',
    'Ferrule_S6',
    'Canopy_S6',
  ],
  7: [
    'Handle_S7',
    'Wrist_Loop_S7',
    'Shaft_Seg1_S7',
    'Joint_S7_0',
    'Shaft_Seg2_S7',
    'Joint_S7_1',
    'Shaft_Seg3_S7',
    'Runner_S7',
    'Ferrule_S7',
    'Canopy_S7',
  ],
  8: [
    'Handle_S8',
    'Wrist_Loop_S8',
    'Shaft_Seg1_S8',
    'Joint_S8_0',
    'Shaft_Seg2_S8',
    'Joint_S8_1',
    'Shaft_Seg3_S8',
    'Runner_S8',
    'Ferrule_S8',
    'Canopy_S8',
  ],
}
